### ISSUE TITLE
Update to php 8.3

### ISSUE THREAD

**Issue by grthi** [datafeedwatch/dfwconnector-magento2#5]
Hello,

Can you fix compatibility of this module with php 8.3?

Thanks

**Comment by wpsamurai** [comment]
@grthi could you please share a little more details where is the problem? We will have a look at this.

**Comment by grthi** [comment]
Hello I will see the exact error with my developer, but regarding your "composer.json" file, it say that the module is not compatible with php 8.3 here

```
    "require": {
        "php": "7.*||~8.1.0||~8.2.0"
    },
```

**Comment by grthi** [comment]
Hello,

So if we try to install your module with php 8.3, it will install the old version 1.0.1

- because if you see the composer.json of this version, there is no requirement for php
=> https://github.com/datafeedwatch/dfwconnector-magento2/blob/1.0.1/composer.json
=> So this old version is the last we can install with php 8.3 in place of the last which must be 3.3.0 normally no?

- if you check the version after 1.0.2
=> https://github.com/datafeedwatch/dfwconnector-magento2/blob/1.0.2/composer.json
=> This one has correctly the php 7 only requirement.


So to fix and let us install your module on php 8.3, we will need you update the composer.json to authorize php 8.3 in it.
=> in this file for me: https://github.com/datafeedwatch/dfwconnector-magento2/blob/3.3.0/composer.json
=> Must update the line like this: 

`
    "require": {
        "php": "7.*||~8.1.0||~8.2.0"||~8.3.0"
    },
`

**Comment by wpsamurai** [comment]
Hello @grthi 

Thank you for all the details. I've just added a task to our backlog to upgrade the module to PHP 8.3. We have to run a few tests first to make sure everything works as expected with PHP 8.3 before we release the new version. I will keep you posted.

**Comment by grthi** [comment]
Hello,

I close the issue, because we see that we are not using anymore your service on our project.

So no problem, happy to can help you.

I let you test on your side the upgrade for php 8.3.

Thanks
